### ISSUE TITLE
Unable to download https://www.atom.io/api/packages/intellij-idea-keymap/versions/0.2.2/tarball: 503

### ISSUE THREAD

**Issue by Xen0n6291** [guylabs/intellij-idea-keymap#10]
Unable to download https://www.atom.io/api/packages/intellij-idea-keymap/versions/0.2.2/tarball: 503

**Comment by guylabs** [comment]
Hi @Xen0n6291 

looks like there is an issue with the atom.io API. I also cannot download it. Maybe this is fixed in a later point in time. Till then you can also get the tarball from here: https://github.com/guylabs/intellij-idea-keymap/archive/v0.2.2.tar.gz

Hope that helps.

Regards,

Guy

**Comment by guylabs** [comment]
UPDATE: I just tested it again and now it works ;).

Does it also work for you?

If yes can you then close the issue?

Thanks and regards,

Guy

**Comment by Xen0n6291** [comment]
Hi,
now it works.

Thanks
