### ISSUE TITLE
Selecting successively increasing code blocks not working as in IntelliJ - Ctrl+W

### ISSUE THREAD

**Issue by pranav-kural** [guylabs/intellij-idea-keymap#12]
There are differences in how the Ctrl+w command works in IntelliJ and how it works with the intellij-idea-keymap.

1. Command Ctrl+w in intelliJ selects the word/code or a block of words or code at caret. The selection happens in both directions, right and left. But when using the Ctrl+w keybinding with the intellij-idea-keymap, the selection happens only in right direction. It's almost the same as Shift+Right Arrow Key, just that it will select one letter with every press, instead of one word.

2. Although the command selects one whole word with every click but in IntelliJ this command could select whole blocks of text and code in few presses, not just one word at a time.

Example:
When the command is used three times at one place (just before "Ut enim"), by holding ctrl and pressing w for three times, following were the selections:

Atom:
![atom-1](https://cloud.githubusercontent.com/assets/17651852/20540953/2a43de9c-b0c9-11e6-9e9f-80358fdf5c5f.PNG)

IntelliJ:
![intelli-1](https://cloud.githubusercontent.com/assets/17651852/20540971/380a6208-b0c9-11e6-91c0-6847039bc610.PNG)

**Comment by guylabs** [comment]
Hi @pranav-kural 

I am sorry for the late response but I could not reply earlier.

yes that is true but the goal is to adopt the shortcuts as much as possible and not to reimplement the same behavior as in Idea. It would surely be possible but I think this is too much effort to implement this logic and out of the scope of this project. But if you need this behavior then you could come up with a pull request and we can check how to integrate this.

Thanks and regards

Guy

**Comment by guylabs** [comment]
I will close the issue due to inactivity. You can reopen it any time.

Thanks and regards,

Guy
