### ISSUE TITLE
Shift-Del work incorrectly with selected symbols

### ISSUE THREAD

**Issue by igorshu** [guylabs/intellij-idea-keymap#13]
When I select some word and press Shift-Del Atom remove whole line.

**Comment by guylabs** [comment]
Hi,

I am sorry for the late response but I could not reply earlier.

Are you using Atom on a Windows machine or what do you mean with `Del` ? The `shift-delete` is a default key binding and it has the `core:delete` function behind it. So this is a default binding of Atom. 

On a Mac if you press `Shift+Fn+Backspace` then the whole line gets also deleted in Idea so the shortcuts are the same in both applications.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @igorshu 

any news on this? 

Thanks and regards

Guy

**Comment by igorshu** [comment]
Hi @guylabs 
I set
`'.platform-win32 atom-workspace atom-text-editor:not([mini]), .platform-linux atom-workspace atom-text-editor:not([mini])':
  'shift-delete': 'unset!'`

and it work properly for me.
