### ISSUE TITLE
Right ALT not supported

### ISSUE THREAD

**Issue by mgzyl** [guylabs/intellij-idea-keymap#14]
There was an issue with atom that is already fixed: https://github.com/atom/atom-keymap/issues/35
However, if you turn the intellij-idea-keymap plugin on then the right alt stops working again.

**Comment by guylabs** [comment]
Hi @mgzyl 

I am sorry for the late response but I could not reply earlier.

Ok I will check that and come back to you. Thanks for mentioning it.

If you now already have a solution you could maybe share it within a pull request if you like.

Thanks and regards,

Guy

**Comment by guylabs** [comment]
HI @mgzyl 

could you maybe tell me your specific setup like keyboard layout, windows or mac, etc. I need some steps to reproduce before I can have a look at it.

Thanks and regards

Guy

**Comment by guylabs** [comment]
Hi @mgzyl 

any news on this?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
I will close the issue due to inactivity. You can reopen it any time.

Thanks and regards,

Guy
