### ISSUE TITLE
Alt-up on Mac is bugged

### ISSUE THREAD

**Issue by Stefan538871** [guylabs/intellij-idea-keymap#16]
'Alt-up' is right now similar to 'cmd-shift-up' and 'alt-shift-up' the same goes for 'Alt-down'

**Comment by guylabs** [comment]
HI @Stefan538871 

sorry for my late reply. `Alt-Up` is `Extend selection` and `Alt-Down` is `Shrink selection` in the official Idea keymap (https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf). 

And for the `CMD-SHIFT-Up` and `ALT-SHIFT-Up` there are no official shortcuts on the keymap. There are some bindings in the `Mac OSX 10.5+` keymap but these are to move lines and statements up and down.

So what exactly is the issue you have?

Thanks and regards

Guy

**Comment by guylabs** [comment]
I will close the issue due to inactivity. You can reopen it any time.

Thanks and regards,

Guy
