### ISSUE TITLE
Improvement: Add some shortcuts

### ISSUE THREAD

**Issue by gquintana** [guylabs/intellij-idea-keymap#2]
|  | Mac | Windows/Linux | Atom command |
| --- | :-: | :-: | :-: |
| Close active tab | cmd-w | ctrl-f4 | core:close |
| Open Settings | cmd-, | ctrl-alt-s | settings-view:open |

These shortcuts may already be the default ones on Mac (cmd-w, cmd-,), but definitely not on Windows/Linux

**Comment by guylabs** [comment]
Hi @gquintana, 

I just added the two shortcuts for Windows and Linux as on the Mac they are already the default shortcuts.

Thanks for pointing this out.

Regards,

Guy

**Comment by gquintana** [comment]
Great!
