### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by OZZlE** [guylabs/intellij-idea-keymap#20]
I followed the installation instructions:
  
    apm install intellij-idea-keymap
    Installing intellij-idea-keymap to /Users/oskar/.atom/packages ✓

Now what? Shortcuts seems to be the same as before..

**Comment by guylabs** [comment]
Hi @OZZlE 

what version of Atom are you using? And what version of the plugin?

Can you check if you enabled the package in the _Settings_ under the _Packages_ section?

Thanks and regards

Guy

**Comment by guylabs** [comment]
I'll close the issue as there was no feedback from @OZZlE. If you still have the issue or need help please reopen the issue.

Thanks and regards

Guy
