### ISSUE TITLE
No way to create new file

### ISSUE THREAD

**Issue by hohmanng** [guylabs/intellij-idea-keymap#21]
Since ctrl+n is taken I suggest to use ctrl+m to create new file, something like this:

> 'atom-workspace, atom-text-editor':
>   'ctrl-m':	'application:new-file'

**Comment by guylabs** [comment]
Hi @gerydeft 

What OS do you use and which keymap do you use on Mac OSX if you use OSX?

Here you see the native shortcuts from IDEA: https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf

Thanks and regards

Guy

**Comment by hohmanng** [comment]
Hi,

I use Ubuntu 18.04, I know the intellij hotkeys, but the new file action is not assigned to any keys by default.

**Comment by guylabs** [comment]
Ok I see. But I think this keymap should map to the ones from IntelliJ IDEA and there is no possibility to create a new file via a shortcut either, except when use `Ctrl + N` in the projects view. I would propose that you use this keymap as default and adapt it to your needs and add the `Ctrl + M` shortcut to create a new file, as I don't want to add custom shortcuts that are not present in the default IntelliJ IDEA keymap.

**Comment by hohmanng** [comment]
Ok, thanks. I already did that. For others who might have this problem:
### keymap.cson
```
'atom-workspace, atom-text-editor':
  'ctrl-m':	'application:new-file'
```

**Comment by guylabs** [comment]
Ok cool thanks a lot!
