### ISSUE TITLE
Make shortcuts work event if no editor tab is opened

### ISSUE THREAD

**Issue by gquintana** [guylabs/intellij-idea-keymap#3]
Some shortcuts should require the editor pane to work:
- Find file
- Show/hide/focus tree view
- Command palette
- Project find

In short, the `atom-text-editor:not([mini])` is sometimes too restrictive

**Comment by guylabs** [comment]
Hi @gquintana,

I now used less restrictive classes for the commands which you mentioned. Thanks for this addition and I hope everything works in Windows and Linux ;).

Thanks and regards,

Guy
