### ISSUE TITLE
can't install successfully,atom version is 1.8.0

### ISSUE THREAD

**Issue by ghost** [guylabs/intellij-idea-keymap#5]
➜  ~ nvm install v0.12.7
###### ################################################################## 100.0%

Now using node v0.12.7 (npm v2.11.3)
➜  ~ sudo apm install intellij-idea-keymap
Password:
Installing intellij-idea-keymap to /Users/qk/.atom/packages
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (http.js:1473:15)
gyp ERR! stack     at Socket.socketOnEnd (http.js:1569:23)
gyp ERR! stack     at Socket.g (events.js:180:16)
gyp ERR! stack     at Socket.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:448:13)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/qk/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/qk/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.36.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/qk/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

➜  ~ nvm use v0.10.40
Now using node v0.10.40 (npm v1.4.28)
➜  ~ sudo apm install intellij-idea-keymap
Installing intellij-idea-keymap to /Users/qk/.atom/packages
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (http.js:1473:15)
gyp ERR! stack     at Socket.socketOnEnd (http.js:1569:23)
gyp ERR! stack     at Socket.g (events.js:180:16)
gyp ERR! stack     at Socket.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:448:13)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/qk/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/qk/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.36.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/qk/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by guylabs** [comment]
Hi @jnuc093,

could you maybe show me the output of `apm --version` ? And are you behind a proxy?

The error looks like it is a low level issue with the connection to `atom.io` and not something related with the plugin itself.

Did you try it again on another internet connection via the mobile network or at your home?

Thanks and regards,

Guy

**Comment by guylabs** [comment]
Hi @jnuc093 

is this still an issue on your side? If yes then please reopen the issue as this is now three moths old.

Thanks and regards,

Guy
